### ISSUE TITLE
Possible to use slide for transition?

### ISSUE THREAD

**Issue by andrewspy** [aaccurso/phaser-state-transition-plugin#12]
Hi,

I am just wondering if there is an option to use "slide" animation state transition. i.e. slide left/right/up/down etc.

Thanks!

Regards,
Andrew

**Comment by aaccurso** [comment]
Hi,

It may be posible if you configure properties like:
```
properties: {
    position: {
      x: 1.4,
      y: 1.4
    }
  }
```

> Note: I don't remember the exact property name for object's position, you should investigate that.

But I wouldn't rely on this, cause I think you won't get a smooth animation, since you wouldn't be using physics to move the object, but its rigidbody's position.

Please get back to me if you try it, and if it works or you found another solution!

Cheers!

**Comment by aaccurso** [comment]
Closing since no feedback was given
